Tidy whitespace and comments

diff --git a/winsnap b/winsnap
--- a/winsnap
+++ b/winsnap
@@ -5,7 +5,7 @@
 #
 # Written by damo <damo@bunsenlabs.org> October 2015
 #
-# The script snaps a window to left or right sides of screen, or top and bottom
+# The script snaps a window to left or right halves of screen, or top and bottom,
 # using X window properties for getting and storing values.
 #
 # Left, right, top, or bottom screen margins can be specified (negative values allowed);
@@ -18,7 +18,9 @@
 #
 ########################################################################
 #
-# TODO:
+# TODO: Account for _NET_WORKAREA with top/bottom snapping if panel only
+# appears on the other monitor.
+#
 ########################################################################
 
 USAGE=$(echo -e "\vUSAGE:\twinsnap [--help|--left|--right|--top|--bottom] <margin>"
@@ -28,7 +30,7 @@ USAGE=$(echo -e "\vUSAGE:\twinsnap [--help|--left|--right|--top|--bottom] <margi
         echo -e "\t--top \t\tsnap to upper screen edge"
         echo -e "\t--bottom \tsnap to bottom screen edge"
         echo
-        echo -e "\tIf no margin is specified, the left and right values set\n\tfor Openbox in rc.xml are used."
+        echo -e "\tIf no margin is specified, the values set\n\tfor Openbox in rc.xml are used."
         echo -e "\tNegative margin values can be used (there may be a panel\n\ton one screen only)."
         echo
         echo -e "\tThe active window will snap to the edge of the screen on\n\twhich it placed."
@@ -38,49 +40,48 @@ USAGE=$(echo -e "\vUSAGE:\twinsnap [--help|--left|--right|--top|--bottom] <margi
 
 ####  FUNCTIONS  ####################################################
 
-function set_prop_int() {    # Add var values to X window properties
+function set_prop_int(){    # Add var values to X window properties
   PROPNAME="$1"
-  VAL="$2"
+  VAL="$2"                         # integer value
   xprop -id "$WINDOW" -f "$PROPNAME" 32i -set "$PROPNAME" "$VAL"
 }
 
-function set_prop_str() {
+function set_prop_str(){
     PROPNAME="$1"
-    VAL="$2"
+    VAL="$2"                         # string value
     xprop -id "$WINDOW" -f "$PROPNAME" 8s -set "$PROPNAME" "$VAL"
 }
 
-function get_prop() {    # Retrieve var values from X window properties
+function get_prop(){    # Retrieve var values from X window properties
   PROPNAME="$1"
   VARNAME="$2"
   eval "$VARNAME"=$(xprop -id $WINDOW $PROPNAME | awk '{print $3}')
 }
 
-function count_monitors() { #test for more than 2 monitors connected.
+function count_monitors(){ #test for more than 2 monitors connected.
     MON=$(xrandr -q | grep -c " connected")
     case $MON in
         1 | 2 ) MONITORS=$MON
                 ;;
-        3 | * ) echo "Script cannot deal with more than 2 monitors yet" >&2
+        3 | * ) echo "Script cannot deal with more than 2 monitors" >&2
                 exit
                 ;;
     esac
 }
 
-function get_screen_dimensions() {   # get net workarea, if panels are present
-    # X pos, Y pos, usable width, usable height
+function get_screen_dimensions(){   # get net workarea, if panels are present
     vals=$(echo $(xprop -root | grep _NET_WORKAREA) | awk '{gsub(",","");print $3,$4,$5,$6}')
-    read valX valY valW valH <<< "$vals"
+    read valX valY valW valH <<< "$vals"    # X pos, Y pos, usable width, usable height
 
     desktopW=$(xrandr -q | awk '/Screen/ {print $8}')  # total desktop width
 
-    # Get monitors geometry and position ( w x h x offset_x offset_y )
+    # Get monitors geometry and position ( w,h,offset_x,offset_y )
     MONS=$(echo $(xrandr -q | awk '/ connected/ {if ($3=="primary") print $1,$4; else print $1,$3}'))
     read monA monAgeom monB monBgeom <<< "$MONS"
 
     monApos=$(echo $monAgeom | awk -F "+" '{print $2}') # get offset_x
     monBpos=$(echo $monBgeom | awk -F "+" '{print $2}')
-    if [[ $MONITORS != 1 ]];then     # test if there are 2 monitors
+    if [[ $MONITORS != 1 ]];then        # test if there are 2 monitors
         if [[ $monApos -lt $monBpos ]]; then
             screenW1=${monAgeom%'x'*}   # width of left screen
             screenW2=${monBgeom%'x'*}   # width of right screen
@@ -89,27 +90,24 @@ function get_screen_dimensions() {   # get net workarea, if panels are present
             screenW1=${monBgeom%'x'*}
         fi
     else
-        screenW1=${monAgeom%'x'*}   # only one screen
+        screenW1=${monAgeom%'x'*}       # only one screen
     fi
     get_ActiveX
 }
 
 function get_ActiveX(){      # X position of active window:
     WINPOS=$(xwininfo -id $WINDOW | grep "Absolute upper-left X")
-
     if [[ ${WINPOS##*' '} -ge $screenW1 ]];then # window is on R monitor
         X_zero=$(( $desktopW - $screenW2 ))
         panelR=$(( $desktopW - $valW - $valX ))
         screenW=$(( $desktopW - $screenW1 - $panelR ))
     else
         X_zero=$valX                            # window is on L monitor
-        #screenW=$(( $screenW1 - $X_zero ))
         screenW=$(( $screenW1 - $X_zero ))
-        
     fi
 }
 
-function get_WM_FRAME() {         # get borders set by WM
+function get_WM_FRAME(){         # get borders set by WM
     # WM sets window frame and border sizes
     # Titlebar height depends on fontsize of Active titlebar
     winEXTENTS=$(xprop -id $WINDOW | awk '/_NET_FRAME_EXTENTS/ {gsub(",","");print $3,$4,$5,$6}')
@@ -119,9 +117,9 @@ function get_WM_FRAME() {         # get borders set by WM
     Yoffset=$(( $BORDER_T + $BORDER_B ))
 }
 
-function get_OB_margins() {
+function get_OB_margins(){
     RC="$HOME/.config/openbox/rc.xml"
-    if [[ -f "$RC" ]]&>/dev/null;then
+    if [[ -f "$RC" ]];then
         TAG="margins"
         RCXML=$(sed -n "/<$TAG>/,/<\/$TAG>/p" "$RC")
         OB_LEFT=$(grep -oPm1 "(?<=<left>)[^<]+" <<< "$RCXML")
@@ -129,15 +127,14 @@ function get_OB_margins() {
         OB_TOP=$(grep -oPm1 "(?<=<top>)[^<]+" <<< "$RCXML")
         OB_BOTTOM=$(grep -oPm1 "(?<=<bottom>)[^<]+" <<< "$RCXML")
     else
-        echo "$RC not found"
+        echo "$RC not found" >&2
         exit 1
     fi
 }
 
-function store_geometry() {  # store values in X window properties
+function store_geometry(){  # store values in X window properties
     # Store number of monitors
     set_prop_int "_MONITORS" "$MONITORS"
-
     eval $(xdotool getactivewindow getwindowgeometry --shell)
     # Set initial geometry and position
     set_prop_int "_INITIAL_DIMENSION_X" "$X"
@@ -167,7 +164,7 @@ function store_geometry() {  # store values in X window properties
     set_prop_int "_OB_MARGIN_B" "$OB_BOTTOM"
 }
 
-function load_stored_geometry() {
+function load_stored_geometry(){    # set var to xprop value
     get_prop "_MONITORS" "num_monitors"
     get_prop "_INITIAL_DIMENSION_X" "initial_x"
     get_prop "_INITIAL_DIMENSION_Y" "initial_y"
@@ -185,7 +182,7 @@ function load_stored_geometry() {
     get_prop "_OB_MARGIN_B" "OB_margin_bottom"
 }
 
-function restore_dimension_geometry() {
+function restore_dimension_geometry(){
     Xpos=$(( initial_x - adjust_X ))    # Correct for frame and border values
     Ypos=$(( initial_y - adjust_Y ))
     if [[ $SNAP = --left ]] || [[ $SNAP = --right ]];then
@@ -203,80 +200,79 @@ function remove_geometry(){
     _OFFSET_X _OFFSET_Y \
     _OB_BORDER_L _OB_BORDER_R _OB_BORDER_T _OB_BORDER_B \
     _OB_MARGIN_L _OB_MARGIN_R _OB_MARGIN_T _OB_MARGIN_B)
-    
+
     for g in ${geom[@]};do
         xprop -id $WINDOW -remove $g
     done
 }
 
-function snap() {
-#    get_screen_dimensions
+function snap(){
     case "$1" in
-        "--left"    )   snap_left $MARGIN
-                        ;;
-        "--right"   )   snap_right $MARGIN
-                        ;;
-        "--top"     )   snap_top $MARGIN
-                        ;;
-        "--bottom"  )   snap_bottom $MARGIN
-                        ;;
-                *   )   echo "Unknown parameter" 2>&1
-                        exit 1 
-                        ;;
+        "--left"  ) snap_left $MARGIN
+                    ;;
+        "--right" ) snap_right $MARGIN
+                    ;;
+        "--top"   ) snap_top $MARGIN
+                    ;;
+        "--bottom") snap_bottom $MARGIN
+                    ;;
+                * ) echo "Unknown parameter" 2>&1
+                    exit 1
+                    ;;
     esac
 }
 
-function snap_left() {
+function snap_left(){
     if (( $1 != 0 ));then
         if (( $1 <= $OB_border_left ));then
-            XPOS=$(( $OB_border_left + $X_zero ))    # don't need OB margin
+            XPOS=$(( $OB_border_left + $X_zero ))   # don't need OB margin
         else
             XPOS=$(( $1 + $OB_border_left + $X_zero ))
         fi
     else
-        XPOS=$(( $OB_margin_left + $X_zero ))  # add OB margin
+        XPOS=$(( $OB_margin_left + $X_zero ))       # add OB margin
     fi
-    WIN_WIDTH_L=$(( ( $screenW / 2 ) - $XPOS - $adjust_X + $X_zero ))
+    WIN_WIDTH_L=$(( ($screenW / 2) - $XPOS - $adjust_X + $X_zero ))
     # Move window
     wmctrl -r :ACTIVE: -b add,maximized_vert && \
     wmctrl -r :ACTIVE: -b remove,maximized_horz && \
     wmctrl -r :ACTIVE: -e 0,$XPOS,0,"$WIN_WIDTH_L",-1
 }
 
-function snap_right() {
+function snap_right(){
     if (( $1 != 0 ));then
         if (( $1 <= $OB_border_right ));then
-            MARGIN_R="$OB_border_right"    # don't need OB margin
+            MARGIN_R="$OB_border_right"      # don't need OB margin
         else
             MARGIN_R=$(( $1 + $OB_border_right ))
         fi
     else
-        MARGIN_R="$OB_margin_right"  # add OB margin to right edge
+        MARGIN_R="$OB_margin_right"         # add OB margin to right edge
     fi
     XPOS=$((( $screenW / 2 ) + $X_zero ))
-    WIN_WIDTH_R=$((( $screenW / 2 ) - $MARGIN_R - $adjust_X ))
+    WIN_WIDTH_R=$(( ($screenW / 2) - $MARGIN_R - $adjust_X ))
     # Move window
     wmctrl -r :ACTIVE: -b add,maximized_vert && \
     wmctrl -r :ACTIVE: -b remove,maximized_horz && \
     wmctrl -r :ACTIVE: -e 0,"$XPOS",0,"$WIN_WIDTH_R",-1
 }
 
-function snap_top() {
+function snap_top(){
     MARGIN_T=$(( $1 + OB_margin_top ))
     YPOS=$(( $valY + $MARGIN_T ))
     WIN_HEIGHT_T=$(( ($valH/2) - $OB_border_top - $OB_border_bottom - $MARGIN_T ))
     # Move window
-    wmctrl -r :ACTIVE: -b remove,maximized_vert && 
+    wmctrl -r :ACTIVE: -b remove,maximized_vert && \
     wmctrl -r :ACTIVE: -b add,maximized_horz && \
     wmctrl -r :ACTIVE: -e 0,-1,"$YPOS",-1,"$WIN_HEIGHT_T"
 }
 
-function snap_bottom() {
+function snap_bottom(){
     MARGIN_B=$(( $1 + OB_margin_bottom ))
     WIN_HEIGHT_B=$(( ($valH/2) - $OB_border_top - $OB_border_bottom - $MARGIN_B ))
     YPOS=$(( $valH/2 + $valY ))
     # Move window
-    wmctrl -r :ACTIVE: -b remove,maximized_vert && 
+    wmctrl -r :ACTIVE: -b remove,maximized_vert && \
     wmctrl -r :ACTIVE: -b add,maximized_horz && \
     wmctrl -r :ACTIVE: -e 0,-1,"$YPOS",-1,"$WIN_HEIGHT_B"
 }
@@ -294,49 +290,48 @@ else
 fi
 WINDOW=$(xdotool getactivewindow)
 #load_stored_geometry
-get_prop "_SNAPPED" "SNAP"      #"Flag" for left/right snapped
+get_prop "_SNAPPED" "SNAP"      #      "Flag" for left/right snapped
                                 #      1: Window is snapped to LEFT
                                 #      2: Window is snapped to RIGHT
                                 #      3: Window is snapped to TOP
                                 #      4: Window is snapped to BOTTOM
 case $SNAP in
-    "such" | "found." ) # xprop returns 'such' or 'found.' upon error
-                count_monitors
-                store_geometry
-                get_screen_dimensions
-                get_prop "_OFFSET_X" "adjust_X"
-                get_prop "_OFFSET_Y" "adjust_Y"
-                get_prop "_OB_BORDER_L" "OB_border_left"
-                get_prop "_OB_BORDER_R" "OB_border_right"
-                get_prop "_OB_BORDER_T" "OB_border_top"
-                get_prop "_OB_BORDER_B" "OB_border_bottom"
-                get_prop "_OB_MARGIN_L" "OB_margin_left"
-                get_prop "_OB_MARGIN_R" "OB_margin_right"
+    "such" | "found." )    # xprop returns 'such' or 'found.' upon error
+            count_monitors
+            store_geometry
+            get_screen_dimensions
+            get_prop "_OFFSET_X" "adjust_X"
+            get_prop "_OFFSET_Y" "adjust_Y"
+            get_prop "_OB_BORDER_L" "OB_border_left"
+            get_prop "_OB_BORDER_R" "OB_border_right"
+            get_prop "_OB_BORDER_T" "OB_border_top"
+            get_prop "_OB_BORDER_B" "OB_border_bottom"
+            get_prop "_OB_MARGIN_L" "OB_margin_left"
+            get_prop "_OB_MARGIN_R" "OB_margin_right"
 
-                case "$1" in
-                    "--left"    )   snap_left $MARGIN
-                                    ;;
-                    "--right"   )   snap_right $MARGIN
-                                    ;;
-                    "--top"     )   snap_top $MARGIN
-                                    ;;
-                    "--bottom"  )   snap_bottom $MARGIN
-                                    ;;
-                            *   )   echo "Unknown parameter" 2>&1
-                                    exit 1 
-                                    ;;
-                esac
-                set_prop_str "_SNAPPED" "$1"
-                ;;
-
+            case "$1" in
+                "--left"  ) snap_left $MARGIN
+                            ;;
+                "--right" ) snap_right $MARGIN
+                            ;;
+                "--top"   ) snap_top $MARGIN
+                            ;;
+                "--bottom") snap_bottom $MARGIN
+                            ;;
+                        * ) echo "Unknown parameter" 2>&1
+                            exit 1
+                            ;;
+            esac
+            set_prop_str "_SNAPPED" "$1"
+            ;;
     "--left" | "--right" | "--top" | "--bottom" )
-                load_stored_geometry
-                get_screen_dimensions
-                if [[ $1 = "$SNAP" ]];then
-                    restore_dimension_geometry
-                else
-                    snap "$1"
-                    set_prop_str "_SNAPPED" "$1"
-                fi
-                ;;
+            load_stored_geometry
+            get_screen_dimensions
+            if [[ $1 = $SNAP ]];then
+                restore_dimension_geometry
+            else
+                snap "$1"
+                set_prop_str "_SNAPPED" "$1"
+            fi
+            ;;
 esac
